### ISSUE TITLE
Some f12 tools documentation links doesn't work

### ISSUE THREAD

**Issue by sarvaje** [MicrosoftEdge/MicrosoftEdge-Documentation#20]
in http://dev.modern.ie some links doesn't work.

e.g. in https://dev.modern.ie/platform/documentation/f12-devtools-guide/console/using-the-console-api/

The links "custom message", "inspectable objects and nodes", etc. don't work.

**Comment by mattwojo** [comment]
Thank you David.

@molant -- this issue is the same as the one below it: https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/issues/14

Anchor links don't work after the markdown is compiled to the site. Can we change the way this compiles? Or is there another way to enter anchor links, besides the typical GitHub markdown format - [Custom messages](#custom-messages)?

**Comment by mattwojo** [comment]
Fixed: https://github.com/MicrosoftEdge/EdgePortal/issues/1658
