### ISSUE TITLE
What about debugger API in extensions roadmap?

### ISSUE THREAD

**Issue by vitalets** [MicrosoftEdge/MicrosoftEdge-Documentation#69]
It is missing here: https://github.com/MicrosoftEdge/MicrosoftEdge-Documentation/tree/master/extensions/API-support/extension-API-roadmap

**Comment by abbycar** [comment]
@vitalets thanks for catching this!
The API roadmap only shows APIs that we are actively considering.
I'll make a note of this on the page to make it more clear :)

**Comment by vitalets** [comment]
@abbycar thank you! 
Anyway are you considering any way for extensions to interact with browser on native level?
I'm interested in it because I develop extension that allows to run Webdriver tests right from browser:
https://github.com/vitalets/autotester

I currently works in Chrome, but I would like to get it working on Edge also.

**Comment by abbycar** [comment]
@vitalets [native messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) is on our roadmap. This isn't a new API though, and will leverage  some other new APIs. I'll add a note of this as well. Thanks for checking out the docs and opening an issue so that we can help clear things up!
